platform :ios, '15.0'

target 'MCPMapDemo' do
  use_frameworks!

  # Pods for MCPMapDemo
  pod 'GoogleMaps', '7.0.0'

  target 'MCPMapDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
